### ISSUE TITLE
Continent 'Americas' is too vague. 

### ISSUE THREAD

**Issue by ktheyss** [vincentarelbundock/countrycode#144]
Can you discriminate between south and north america?

**Comment by vincentarelbundock** [comment]
The dictionary process will now automatically be built from online source. Can you identify a better source of continent information and write a web scraper for it?

If so, contribute here: http://github.com/vincentarelbundock/countryyear

**Comment by cjyetman** [comment]
This is also an excellent use case for the fairly new custom dictionary feature. See the [README ](https://github.com/vincentarelbundock/countrycode/blob/master/README.md#custom-country-codes-dictionaries)for an explanation and example.

**Comment by cjyetman** [comment]
I opened an [issue ](https://github.com/vincentarelbundock/countryyear/issues/19)over in countryyear to track ideas for well known 'continent' conventions.

**Comment by cjyetman** [comment]
To directly answer the question so that we can close this issue...

At the moment, countrycode does not have a continent destination code that discriminates between North and South America. This can currently be achieved by using the custom dictionary feature and providing your own dictionary that has a continent destination with what you need. In code, that would look something like...
```r
countrycode(cntry_vect, origin = 'country.name', destination = 'my_continent', 
            custom_dict = continent_dict, origin_regex = TRUE)
```
In the future, countrycode may inherit more continent destination codes from the countryyear project. If anyone has suggestions and/or links to well know continent specifications, please let us know [here](https://github.com/vincentarelbundock/countryyear/issues/19)
