### ISSUE TITLE
get_world_bank is broken

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#154]

**Comment by cjyetman** [comment]
We've used both of these links previously:
http://databank.worldbank.org/data/AjaxDownload/FileDownloadHandler.ashx?filename=Data_Extract_From_World_Development_Indicators_Metadata.xlsx&filetype=METADATA&language=en
http://databank.worldbank.org/data/AjaxDownload/FileDownloadHandler.ashx?filename=Data_Extract_From_World_Development_Indicators_Metadata.xls&filetype=METADATA&language=en

One's a XLS, the other's a XLSX. They were both discovered by watching what happens when you ask to download the metadata while in the databank viewer. Maybe these are sporadically failing because a new request out of the blue doesn't have the proper Referer in the http headers or there's no proper session ID?

Anyway, maybe this is a better source because it's linked directly from [this page](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups) and appears to be updated periodically:
http://databank.worldbank.org/data/download/site-content/CLASS.xls

I haven't verified if it has the same codes and/or if it's as complete as the others, but I'm optimistic.

**Comment by vincentarelbundock** [comment]
OK, I have time now, so I'll look into this.

**Comment by vincentarelbundock** [comment]
It looks like the codes in there are exactly equal to ISO3c.

**Comment by cjyetman** [comment]
Except that it includes Channel Islands (CHI) and Kosovo (XKX), which are not officially in iso3c. I think I suggested putting this World Bank code set in here because, although the change is minor, the World Bank data is probably used so often that it's worth having its own code, rather then insisting that users do something like this to work around it...
```r
custom_match <- c(CHI = 'Channel Islands', XKX = 'Kosovo')
countrycode(wbdata$code, 'iso3c', 'country.name', custom_match = custom_match)
```

**Comment by vincentarelbundock** [comment]
Right! For some reason I missed these.

https://github.com/vincentarelbundock/countrycode/commit/78d591f54946fe09d6b969c3ba7d84a896a9f26d

```
> library(countrycode)
> countrycode('Channel Islands', 'country.name', 'wb')
[1] "CHI"
> countrycode('Channel Islands', 'country.name', 'iso3c')
[1] NA
Warning message:
In countrycode("Channel Islands", "country.name", "iso3c") :
  Some values were not matched unambiguously: Channel Islands
```
