### ISSUE TITLE
Eu28

### ISSUE THREAD

**Issue by leoniedu** [vincentarelbundock/countrycode#159]
There are 29 countries listed as EU28. Is that correct? I believe Liechtenstein shouldn´t be listed.

**Comment by vincentarelbundock** [comment]
Good catch!

Fixed in https://github.com/vincentarelbundock/countrycode/commit/62519070568f9ea498a39aebf850a92339638678

I recommend you install from github, as I am unlikely to make a CRAN release short term. There are lots of big changes in master, and I want to test the current version for a while before releasing.
