### ISSUE TITLE
(North/South) Vietnam

### ISSUE THREAD

**Issue by julianhinz** [vincentarelbundock/countrycode#16]
I believe COW project uses 816 for Vietnam instead of 817, which was assigned to South Vietnam.

**Comment by vincentarelbundock** [comment]
ooops, not sure what happened.

I'm totally overcommitted for the next 3-4 weeks, so it's unlikely I'll get to this very soon, sorry!

Isn't the lookup CSV just moved to dictionary/data_static.csv ?

**Comment by cjyetman** [comment]
> Isn't the lookup CSV just moved to dictionary/data_static.csv ?

It only has the codes that are not auto-collected/generated. So for instance, I could not look up which commit changed the cown code for Vietnam from 816 to 817.

**Comment by vincentarelbundock** [comment]
hmm, okay. So basically, you want to save a version of ``countrycode::codelist`` as CSV in the repo. sounds reasonable.

**Comment by vincentarelbundock** [comment]
Also, before closing this issue, we should write a test.

**Comment by cjyetman** [comment]
I'm pretty confused about how to fix this, so I'm leaving here some info I've been collecting...

The current regex in [data_static.csv](https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/data_static.csv) for Vietnam, which should be unique and only refer to one possible entity is: `^(?!.*republic).*viet.?nam|^(?=.*socialist).*viet.?nam`

---

There are 3 entities that could be able uniquely distinguished:

South Vietnam 1954-1975
possible names: South Vietnam, Republic of Vietnam
CoW: RVN - 817

North Vietnam / Vietnam 1954-1975
possible names: North Vietnam, Democratic Republic of Vietnam
CoW: DRV - 816

Vietnam 1976-present
possible names: Vietnam, Viet Nam, Socialist Republic of Vietnam
CoW: DRV - 816

---

Since Vietnam 1976-present is the only one that currently exists, following the philosophy of only converting codes that are valid in the current year, there should be only one regex, and it should...

match any of: "Vietnam", "Viet Nam", and "Socialist Republic of Vietnam"

exclude any of: "South Vietnam", "Republic of Vietnam", "North Vietnam",  and "Democratic Republic of Vietnam"

That makes for a somewhat complicated regex, and it means that the current one probably needs to be adapted.

---

The dictionary [build code for CoW](https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/get_cow.R#L24-L33) makes some manual changes to the Vietnam info for cown:RVN (South Vietnam 1954-1975) and cown:DRV (North Vietnam 1954-1975 and Vietnam 1976-present), and I'm not 100% sure what the ultimate intended outcome of that is. Must keep in mind that the panel dataset is collected simultaneously, so we cannot simply remove all cown:RVN references.

**Comment by vincentarelbundock** [comment]
Consolidating Vietname issues here https://github.com/vincentarelbundock/countrycode/issues/207
