### ISSUE TITLE
Improve warnings

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#160]
``countrycode`` checks whether ambiguous matches are present based on all factor levels rather than just the observed vector. This can produce weird warnings:
```
> library(countrycode)
> z = c('Canada', 'Junk', 'United States')
> ifelse(z != 'Junk', countrycode(z, 'country.name', 'iso3c'), 'Bad')
[1] "CAN" "Bad" "USA"
Warning message:
In countrycode(z, "country.name", "iso3c") :
  Some values were not matched unambiguously: Junk

```

**Comment by cjyetman** [comment]
actually, it ignores levels that are not found in the values...
```r
> library(countrycode)
> z <- factor(c('Canada', 'Junk', 'United States'))
> y <- z[c(1,3)]
> y
[1] Canada        United States
Levels: Canada Junk United States
> countrycode(y, 'country.name', 'iso3c')
[1] "CAN" "USA"
```
---

Maybe you're referring to confusion with the warning message "Some values were not matched unambiguously: Junk", which could be understood to imply that 'Junk' matched more than once, but it actually means that 'Junk' was not matched (unambiguously) at all?

for instance...
```r
> countrycode('Junk', 'country.name', 'iso3c')
[1] NA
Warning message:
In countrycode("Junk", "country.name", "iso3c") :
  Some values were not matched unambiguously: Junk
```
---
Side note:
This is a good case for the `cutsom_match` argument, and as a side benefit, it avoids this warning because you're providing a custom match...
```r
> library(countrycode)
> z = c('Canada', 'Junk', 'United States')
> 
> countrycode(z, 'country.name', 'iso3c')
[1] "CAN" NA    "USA"
Warning message:
In countrycode(z, "country.name", "iso3c") :
  Some values were not matched unambiguously: Junk

> 
> ifelse(z != 'Junk', countrycode(z, 'country.name', 'iso3c'), 'Bad')
[1] "CAN" "Bad" "USA"
Warning message:
In countrycode(z, "country.name", "iso3c") :
  Some values were not matched unambiguously: Junk

> 
> countrycode(z, 'country.name', 'iso3c', custom_match = c('Junk' = 'Bad'))
[1] "CAN" "Bad" "USA"
```

**Comment by vincentarelbundock** [comment]
Right. I get the confusion comes from my misinterpretation of what `ifelse` does internally.

Thanks for taking a look and helping me clarify.

**Comment by cjyetman** [comment]
I think the warning message could be better... my current preference would be to *always* warn if a value matches multiple values in the origin vector with `Some values were not matched unambiguously: XXX`, and only if `warn = TRUE`, then also give a different warning if a value is not matched at all in the origin vector like `Some values were not matched: YYY`.

There was discussion of this here #94, and the change was made in #120

**Comment by vincentarelbundock** [comment]
Agreed. But then why not say "some origin values could match multiple destination values". Would be clearly than "unambiguously".

We also need to improve printing. In my practice, the output isn't always clear.

**Comment by cjyetman** [comment]
The reason it gives the (ambiguous) warning `Some values were not matched unambiguously` is because the warning serves both purposes:
1. the value was matched multiple times in the origin vector
2. the value was not matched at all in the origin vector

The current warning technically satisfies both those possibilities, though it very strongly implies the first, which easily leads to confusion. I think we should detect and respond to those two events separately and differently.

**Comment by vincentarelbundock** [comment]
Absolutely. I'm off to a conference in the next few days, but will try to take a look when I come back.
