### ISSUE TITLE
Sudan iso3n

### ISSUE THREAD

**Issue by molliejmcdowell** [vincentarelbundock/countrycode#174]
Hi,
It looks like you fixed this in a previous version. I am running v0.19.

`> countrycode("Sudan", "country.name", "iso3n")`
`[1] 736`

(Should be 729)

**Comment by cjyetman** [comment]
There’s a new release version 1.00.0 on CRAN. Can you try updating and letting us know if it’s still an issue please?

**Comment by vincentarelbundock** [comment]
I just tried, and it's fixed in the latest version.

**Comment by molliejmcdowell** [comment]
Ok, I suppose the issue is that the package update is not available through CRAN for me. Easy enough to change Sudan's code manually.

**Comment by cjyetman** [comment]
You should check your default repo, because it's definitely on the main CRAN repo here https://cran.r-project.org/package=countrycode

You can explicitly set the repo in the `install.packages` command, like this...
```r
install.packages('countrycode', repos = 'http://cran.r-project.org')
```

You can also install directly from the specific version's source code link there, like this...
```r
install.packages('https://cran.r-project.org/src/contrib/countrycode_1.00.0.tar.gz', repos = NULL)
```

**Comment by cjyetman** [comment]
You could also use the `custom_match` argument (in >= v0.19) to force the result you want for specific countries, like so...
```r
countrycode("Sudan", "country.name", "iso3n", custom_match = c(Sudan = 729))
```

**Comment by molliejmcdowell** [comment]
Got it, thanks for the help!
