### ISSUE TITLE
Regex with custom dict,  version 1.00 only

### ISSUE THREAD

**Issue by jsga** [vincentarelbundock/countrycode#177]
Hello,

here it is a small example, run with two different versions of the package: 0.19 Vs 1.0

The preliminaries:
```
library(devtools)
install_version("countrycode", version = "0.19")
library(countrycode)
sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] countrycode_0.19 devtools_1.13.2 

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.4.4 R6_2.2.2       tools_3.4.4    withr_2.1.1    curl_3.1       yaml_2.1.14    memoise_1.1.0  digest_0.6.15 
````
And now the example:
```
# Load basic country list and 
custom_code = countrycode::countrycode_data
# Create custom list of countrynames. Copy existing one for this example.
custom_code$custom_names = custom_code$country.name.en
# As an example: change name of the USA to United States of America
idx = which(custom_code$custom_names == "United States")
custom_code$custom_names[idx] = "United States of America"
# Find country name
countrycode("United States of America",'country.name','custom_names', custom_dict = custom_code, origin_regex =  TRUE)

[1] "United States of America"
```

Great! It works. Now we install the latest version from [CRAN](https://CRAN.R-project.org/package=countrycode) and repeat the same example

```
> library(countrycode)
> packageVersion("countrycode")
[1] ‘1.0.0’
> 
> # Load basic country list and 
> custom_code = countrycode::codelist
> # Add custom list of countrynames
> custom_code$custom_names = custom_code$country.name.en
> # As an example: change name of the US
> idx = which(custom_code$custom_names == "United States")
> custom_code$custom_names[idx] = "United States of America"
> # Find country name
> countrycode("United States of America",'country.name','custom_names', custom_dict = custom_code, origin_regex =  TRUE)
Error in countrycode("United States of America", "country.name", "custom_names",  : 
  Origin code not supported by countrycode or present in the user-supplied custom_dict.
> 
````
Thanks!

**Comment by cjyetman** [comment]
Not sure why that works in v0.19, but the reason it does **not** work in v1.0.0 is because there is no column/variable named `country.name` in `custom_code`. The reason why `origin = 'country.name'` works when not using a custom dictionary is because a [special catch](https://github.com/vincentarelbundock/countrycode/blob/df1446dc705d9fb834308ab500a3308abc00dc38/R/countrycode.R#L65-L67) was added when the different language regex patterns were added to ensure backwards compatibility (technically what's happening is when `origin = 'country.name'` is used, it assumes that you want `origin = 'country.name.en'` when using the default dictionary). That auto conversion from `origin = 'country.name'` to `origin = 'country.name.en'` could be done for custom dictionaries also, but I imagine that could ending causing problems for people or use cases where a non-English language is preferred.

**Comment by cjyetman** [comment]
For extra clarification, if you use `origin = "country.name"` with `custom_dict = custom_code` and `origin_regex =  TRUE`, then `custom_code$country.name` needs to be a variable with regex codes in it.

What you are probably trying to do is this:
```r
library(countrycode)

custom_code <- countrycode::countrycode_data
custom_code$custom_names <- custom_code$country.name.en
idx <- which(custom_code$custom_names == "United States")
custom_code$custom_names[idx] = "United States of America"

packageVersion("countrycode")
countrycode("United States of America", "country.name.en.regex", "custom_names", 
            custom_dict = custom_code, origin_regex = TRUE) 
```

If all you want is for `"United States of America"` to be converted to `"United States of America"` instead of the default `"United States"` (or some other specific country name or set of names), I strongly suggest using the `custom_match` argument like so:
```r
library(countrycode)

countrycode("United States of America", "country.name", "country.name", 
            custom_match = c("United States of America" = "United States of America")) 
```

**Comment by cjyetman** [comment]
and the change occurred in this commit 730896901878ec6435626ac5fc1465fdf66591da

**Comment by jsga** [comment]
Thanks for the detailed explanation! :+1:

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report anyway, and thanks to @cjyetman !
