### ISSUE TITLE
Alternate parameter names

### ISSUE THREAD

**Issue by EvaMaeRey** [vincentarelbundock/countrycode#204]
Excellent and useful package! 

Quick question.  I find that if I write out all parameters, which I like to do teaching, countrycode() tends to be some of the longest lines of code. 

I'm wondering how hard it would be and if you think it might be worth it be to add some alternate parameter names (like "color" and "colour" in ggplot).

My preference:  
countrycode::countrycode(x = country, from = "country.name", to = "country.name")

Thanks!

**Comment by cjyetman** [comment]
Thanks for the idea!

My initial feeling is that this would unfortunately make things a bit too messy, but giving a second thought, this is probably feasible with a short bit of code at the beginning of the function that sorts out the arguments and then everything below would stay the same.

If @vincentarelbundock gives it a thumbs up, I could make a prototype for it.

**Comment by cjyetman** [comment]
I came up with these two prototypes...

prototype A
```r
test <-
  function(sourcevar, x = NULL) {
    if (missing(sourcevar) & exists("x")) sourcevar <- x
    return(sourcevar)
  }

test("germany")
# [1] "germany"
test(x = "us")
# [1] "us"
test("germany", x = "us")
# [1] "germany
test(y = "us")
# Error in test(y = "us") : unused argument (y = "us")
test("germany", y = "us")
# Error in test("germany", y = "us") : unused argument (y = "us")
```

prototype B
```r
test <-
  function(sourcevar, ...) {
    if (missing(sourcevar) & !is.null(list(...)$x)) sourcevar <- list(...)$x
    sourcevar
  }

test("germany")
# [1] "germany
test(x = "us")
# [1] "us"
test("germany", x = "us")
# [1] "germany
test(x = "us", sourcevar = "germany")
# [1] "germany
test(y = "us")
# Error in test(y = "us") : 
#   argument "sourcevar" is missing, with no default
test("germany", y = "us")
# [1] "germany
```

prototype A pollutes the function definition with additional arguments, so prototype B is probably preferable, but note that it requires adding the `...` argument, which means if a user adds an argument that doesn't exist (e.g. `y`), no error is thrown, which does not affect the functionality, but loses the error warning to the user that they passed an unused parameter (which might not be such a bad thing).

I found an approach to changing parameter names here: https://ropensci.org/technotes/2017/01/05/package-evolution/

the equivalent here would be...

```r
test <- 
  function(sourcevar, x) {
    calls <- names(sapply(match.call(), deparse))[-1]
    if(any("x" %in% calls)) {
      sourcevar <- x
    }
    sourcevar
}

test("germany")
# [1] "germany
test(x = "us")
# [1] "us"
test("germany", x = "us")
# [1] "us"
test(x = "us", sourcevar = "germany")
# [1] "us"
test(y = "us")
# Error in test(y = "us") : unused argument (y = "us")
test("germany", y = "us")
# Error in test("germany", y = "us") : unused argument (y = "us")
```

I think this is a dangerous approach since `x` supersedes `sourcevar`.

**Comment by cjyetman** [comment]
also note, because of the way argument matching works in R by default, you can use abbreviated argument names...

```r
countrycode(sourcevar = "usa", origin = "iso3c", destination = "country.name")
# [1] "United States"
countrycode(s = "usa", origin = "iso3c", d = "country.name")
# [1] "United States"
```

You can't use `o = "iso3c"` because there is also an `origin_regex` argument, so it won't know which to match... you have to use the exact match `origin`.

**Comment by vincentarelbundock** [comment]
Yeah, if I were to do this again, I would almost certainly choose different argument names (to/from are great). But this is where we are, and too many people have code with those to change now, I think.

I agree that both solutions are kind of clunky. I don't like adding too many arguments because `?countrycode` will become unreadable.

W.r.t. solution B, we could always throw our own error if `...` includes unused arguments. But that feels a bit hackish.

I went through various phases in my R life, and am now at a point in the cycle where I embrace long variable and argument names. My `countrycode` calls mostly span multiple lines, and I feel it just adds to readability, but I understand why this would bug some.

To be honest, I'm not sure we should implement this. It's the kind of thing that would obviously have been better from the start, but that will now require a hack that adds difficulty to maintainability. 

@cjyetman 's prototypes are cool, but they do kind look like magic when you look at them for the first time. Not sure if that's a good thing, unless the feature is really necessary.

**Comment by EvaMaeRey** [comment]
Thanks to both of you for your thoughtful consideration and explanation of
why you probably don't want to go down this route.  Thought it was worth
asking given my preference for naming parameters and how frequently I use
and helpful ive found countrycode.  Thanks too Vincent for the push on
reveal w/o code display.  It was fun to work out.  Implementation is a bit
messy... More to do!
