### ISSUE TITLE
Polity IV “scode” not implemented

### ISSUE THREAD

**Issue by NilsEnevoldsen** [vincentarelbundock/countrycode#25]
Polity IV uses "scode", supposedly (and mostly) similar to COW codes, but there appear to be differences:
- ETI -> NA (Should match Ethiopia--historical issue?)
- FJI -> NA (Should match Fiji)
- IVO -> NA (Should match Ivory Coast)
- KOS -> NA (Should match Kosovo)
- MNT -> NA (Should match Montenegro)
- PKS -> NA (Should match Pakistan--historical issue?)
- RUM -> NA (Should match Romania)
- SER -> NA (Should match Serbia)
- VIE -> NA (Should match Vietnam)
- ZAI -> NA (Should match Democratic Republic of Congo)

**Comment by cjyetman** [comment]
The following code pulls all of the country lookup tables directly out of the PolityIV codebook PDF, picks out only the most recent version of a country with more than one SCODE, and adds them to a custom dictionary to use with countrycode (requires current dev version of countrycode). It matches all of the above as expected, except for PKS->Pakistan because PKS is the SCODE for Pakistan 1947-1971 and PAK is the SCODE for Pakistan 1972-present.

@vincentarelbundock Maybe scraper code like this could be integrated somehow in the utilities to add country codes to [data/countrycode_data.csv](https://github.com/vincentarelbundock/countrycode/blob/master/data/countrycode_data.csv) programmatically instead of manually? I'm working on a few that I could submit (I'm working on a similar project in parallel where there's a lot of crossover).
```r
library(tabulizer)
library(countrycode)
library(tidyr)
library(dplyr)

pdfurl <- 'http://www.systemicpeace.org/inscr/p4manualv2015.pdf'
df <- tabulizer::extract_tables(pdfurl, pages = 45:50, method = 'data.frame', na.strings = '')
df <- Reduce(rbind, df)

p4current <- 
  df %>% 
  dplyr::mutate_each(funs(trimws), Country, SCODE) %>% 
  tidyr::fill(Country, SCODE, CCODE) %>% 
  dplyr::mutate(country.name = countrycode(Country, 'country.name', 'country.name')) %>% 
  dplyr::filter(!is.na(country.name)) %>% 
  dplyr::group_by(country.name) %>% 
  dplyr::filter(n() == 1 | (country.name == 'Yugoslavia' & End.Year == 2006) | (n() > 1 & is.na(End.Year))) %>% 
  dplyr::ungroup()

cust_dict <- countrycode_data
matchidxs <- match(cust_dict$country.name.en, p4current$country.name)
cust_dict$p4scode <- p4current$SCODE[matchidxs]
cust_dict$p4ccode <- p4current$CCODE[matchidxs]

p4cntryrmisses <- c('Ethiopia', 'Fiji', 'Ivory Coast', 'Kosovo', 'Montenegro', 'Pakistan', 'Romania', 'Serbia', 'Vietnam', 'Democratic Republic of Congo')
p4scodemisses <- c('ETI', 'FJI', 'IVO', 'KOS', 'MNT', 'PKS', 'RUM', 'SER', 'VIE', 'ZAI')

countrycode(p4cntryrmisses, 'country.name.en.regex', 'p4scode', dictionary = cust_dict, origin_regex = T)
countrycode(p4scodemisses, 'p4scode', 'country.name.en', dictionary = cust_dict, origin_regex = F)
```

**Comment by vincentarelbundock** [comment]
A few thoughts:

1. Refactoring the dictionary building process is probably a good idea, but I'm not sure it's worth going through the trouble unless we address the main shortcoming of countrycode: mismatch between codes in different years.

2. To me, the most appealing option would be to build a country-year version of the dictionary, and to use only the latest year by default when conversion is cross-sectional.

3. I've already moved pretty far in that direction (not public until now): https://github.com/vincentarelbundock/countryyear

4. I agree that building programmatically from original sources is much better, but I do think we should store the original files (license permitting) somewhere in case the remotes suddenly disappear.

5. Polity has a convenient Excel file, so no need to parse the PDF.

**Comment by cjyetman** [comment]
Polity IV scode and ccode added in #114
