### ISSUE TITLE
Where is "wb.name"? (Country name from World Bank)

### ISSUE THREAD

**Issue by xfim** [vincentarelbundock/countrycode#250]
I am afraid I am not able to find the "wb.name" in the codelist table. It used to work a couple of months ago. But now it has disappeared. 

I am trying to look for commits that may have affected it, to see what may have happened, but without luck. 

Is there any way to get it back? 

Thank you very much,

**Comment by cjyetman** [comment]
I can confirm that this is a change from v1.1.3 to v1.2.0. I suspect this is due to changes in the build process which gave preference to the WB scraper versus the backup dataset. It also appears that the `wb.name` destination code was a relic from some long time ago, which is why it is/was so difficult to find any reference to it in this repo... it was in the backup dataset, but not documented in the help files (and I take that to mean, not actually intended to be included).

This could easily be fixed by modifying the WB scraper here https://github.com/vincentarelbundock/countrycode/blob/master/dictionary/get_world_bank.R
though I would suggest renaming from `wb.name` to `wb_name` to conform with the [tidyverse style guide](https://style.tidyverse.org/syntax.html#object-names) (though that's a bigger issue since we currently have a mix of multi-word code names using `.` and `_` as separators).

In regards to getting it back... you could temporarily revert to a previous version of `countrycode` with, for instance, `devtools::install_github('vincentarelbundock/countrycode', ref = '1.1.3')`. Alternatively, you could use one of the many country name destination codes currently available, e.g. `iso.name.en`, `un.name.en`, `wvs.name`, `cldr.name.en`, `cldr.short.en`, etc.... or simply `country.name`.

**Comment by xfim** [comment]
Thank you @cjyetman, for your detailed explanation and possible solutions.

I have temporarily moved back to v1.1.3. The problem, though, is still there. I have no experience with the package, and the file that you mention would be hard for me to change. In any case, I agree with wb.name to wb_name.

The problem with the country names is that I want to precisely use the World Bank to move to other formats, and `wb.name` and `country.name` are not the same for several countries:

```
select(codelist, country.name.en, wb.name) %>%
filter(country.name.en != wb.name)
```

**Comment by cjyetman** [comment]
You may need to restart your R session before the package is really available after downgrading (I did).

If you’re converting from one format to another (in terms of country names or codes), `countrycode` excels at that, so there may be an alternate way to achieve what you want, maybe even a better way. Many datasets include both a country name and a country code, so it might be possible to use the code instead of the name. Or, if you’re merging two datasets, you could convert the country names in both datasets to a common country name destination that is available, and merge on that. 

If you can provide a minimal reproducible example, we may be able to help find a solution. 

The information about what to change to fix the issue was targeted at myself and the other maintainers.

**Comment by xfim** [comment]
It was more of a convenience issue (the scripts were written for dealing with "wb.name"). I can use a workaround using the IMF code (imf in `countrycode`), although the "code" used in the dataset is a three digits that I have note been able to understand. And of course I would like to have the "Country" variable as the old "wb.name", as it is using the same World Bank names.

For the reproducible example, I am refering to the financial crisis dataset from the IMF (https://www.imf.org/en/Publications/WP/Issues/2017/04/03/Fiscal-Crises-44795)

```
library(dplyr)
library(countrycode)
library(readxl)

url <- "https://www.imf.org/~/media/Files/Publications/WP/2017/datasets/wp1786.ashx"
tmp <- tempfile()
download.file(url, tmp)
file <- unzip(tmp, files = "DB_publication.xlsx")
orig <- read_excel(file, sheet = "db.", skip = 1)

crises <- orig %>%
  select(Country = country, 
         country.code = code, 
         imf.code = code) %>%
  unique()
```

**Comment by xfim** [comment]
Although there is indeed one case in an IMF-related dataset that only the country name is used (wb.name). I am refering to the Historical Public Debt Database (https://www.imf.org/external/datamapper/DEBT1@DEBT/OEMDC/ADVEC/WEOWORLD).

In this precise case the convenience of having the World Bank name is essential. Any hint is appreciated.

```
url <- "https://www.imf.org/external/datamapper//export/excel.php?indicator=DEBT1"
tmp <- tempfile()
download.file(url, tmp)
imf.debt <- read_excel(tmp, na = "no data") %>%
  tibble() %>%
  select(Country = `DEBT (% of GDP)`) %>%
  unique()


```

**Comment by vincentarelbundock** [comment]
Thanks a lot for opening this issue. Feedback and requests like this are always very valuable!

Even if the wb.name column disappeared from the codelist, it turns out that we still host World Bank country names on Github. The problem is that there is no UNIQUE set of country names. I recommend you spend some time looking at the three different files I copy below, which we got from three different sources of World Bank data. You'll notice that the World Bank itself does not write each name in a consistent format across its different websites and databases.

This highlights a more general problem: In my humble opinion, it is a *bad* idea to rely on country names for merging or cleaning data. Country names have way too many different spellings or encodings to be useful for programmatic purposes. The whole point of country codes (generally, not this package) is precisely to *not* use ambiguous country names.

Given that the World Bank does not appear to have a single set of "official" country names, my inclination would be *against* re-instating the old ones. Instead, analysts should focus on a well-known, well-defined, standardized way of identifying  countries, such as ISO-3c. 

If you still need the World Bank names for a specific use-case, you can easily download one of the files below and use the `custom_dict` argument in `countrycode` to convert back and forth from those data.

Of course, I'm open to counterargument.

```r
world_bank_databank <- read.csv('https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/dictionary/data_world_bank.csv')
world_bank_api <- read.csv('https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/dictionary/data_world_bank_api.csv')
world_bank_region <- read.csv('https://raw.githubusercontent.com/vincentarelbundock/countrycode/master/dictionary/data_world_bank_region.csv')

# pairwise comparison 1
setdiff(world_bank_databank$country, world_bank_api$country)
setdiff(world_bank_api$country, world_bank_databank$country)

# pairwise comparison 2
setdiff(world_bank_databank$country, world_bank_region$country)
setdiff(world_bank_region$country, world_bank_databank$country)

# pairwise comparison 3
setdiff(world_bank_api$country, world_bank_region$country)
setdiff(world_bank_region$country, world_bank_api$country)
```

**Comment by xfim** [comment]
I'm definitively not going to counteargue here, @vincentarelbundock: code names are, and have always been, a nightmare. iso3c should be the default also for me. In fact, the first package in `R` that my students learn is precisely this one. And the amount of pain saved in the last years is not measurable. So thank you! A blessing for comparative politics in my case. 

Having said so, and following my previous example, it is unclear to my which of the three dictionaries this specific debt database is using:

```
left_join(unique(select(imf.debt, Country)), 
                   world_bank_databank,
                   by = c("Country" = "country")) %>%
  filter(is.na(wb)) %>%
  data.frame()

# Is it world_bank_api?
left_join(unique(select(imf.debt, Country)), 
                   world_bank_api,
                   by = c("Country" = "country")) %>%
  filter(is.na(wb_api2c)) %>%
  data.frame()

# Is it world_bank_region?
left_join(unique(select(imf.debt, Country)), 
                   world_bank_region,
                   by = c("Country" = "country")) %>%
  filter(is.na(region)) %>%
  data.frame()
```

In the first case we have 26 missings, in the second 24 and 25 in the third. So my guess is that they do not come indeed from a World Bank set of names. Any clue?

Just thinking about it, wouldn't it be nice to have some sort of function where you input a vector of country names, their unique names are then compared to the possible combinations of `countrycode` and as an output you have a probability of matching any of the possible country names available in the package? Like a kind of aid to help you manually guess "orig" or "dest" when you don't know it. I can try it, if you see it has potential.

**Comment by vincentarelbundock** [comment]
I guess I'm still not clear on the use-case. Why don't you just change county names to ISO3 in BOTH databases, and then merge them based on that. We put in a lot of effort so that this should work in most cases:

```r
countrycode(dat$countryname, 'country.name', 'iso3c')
```

**Comment by xfim** [comment]
OK, my fault. I tried all sorts of types before, but not the most obvious, the "country.name". With the "wb.name" it was working and that did the trick. Now with the new version I simply didn't tried "country.name". Thank you.

The point about having the three World Bank names, or a function helping to decide which to use is still valid. But I see it now as less important, so I'm going to close the issue.

**Comment by vincentarelbundock** [comment]
Thanks again for engaging. Sometimes I've found there's just no perfect answer. But I'm glad you found something that works for your purposes!

**Comment by cjyetman** [comment]
@xfim in case you did not realise... when you use `origin = "country.name"`, `countrycode` will use a fancy, built-in set of regex codes which allows it to recognise numerous variations of country names, so it does not have to be an exact match. For instance....

``` r
library(countrycode)

country_names <- c('USA', 'United States')

countrycode(country_names, 'country.name', 'iso3c')
#> [1] "USA" "USA"

countrycode(country_names, 'country.name', 'country.name')
#> [1] "United States" "United States"

countrycode(country_names, 'country.name', 'cldr.short.en')
#> [1] "US" "US"
```

 additionally, `countrycode` has built-in German regexes as well, which you can use like this...

``` r
library(countrycode)

country_names_de <- c('Deutschland', 'Spanien')

countrycode(country_names_de, 'country.name.de', 'iso3c')
#> [1] "DEU" "ESP"

countrycode(country_names_de, 'country.name.de', 'country.name')
#> [1] "Germany" "Spain"

countrycode(country_names_de, 'country.name.de', 'country.name.de')
#> [1] "Deutschland" "Spanien"

countrycode(country_names_de, 'country.name.de', 'cldr.short.de')
#> [1] "Deutschland" "Spanien"
```

and finally, the latest version of `countrycode` added a new function which can convert country names in different languages at the same time, like this...

``` r
library(countrycode)

country_names <- c('ジンバブエ', 'USA', 'United States', 'Germany', 'Deutschland')

countryname(country_names, 'iso3c')
#> [1] "ZWE" "USA" "USA" "DEU" "DEU"

countryname(country_names, 'country.name.en')
#> [1] "Zimbabwe"      "United States" "United States" "Germany"      
#> [5] "Germany"

countryname(country_names, 'cldr.short.en')
#> [1] "Zimbabwe" "US"       "US"       "Germany"  "Germany"
```

**Comment by xfim** [comment]
Yes, indeed I didn't realize. That's the reason why I was asking, and proposing something that it is already implemented. I am sorry for the misunderstanding, @vincentarelbundock . Thank you @cjyetman for pointing this out.

I was assuming that the `codelist` table was the match, and therefore any country not in the `country.name` in that table needed to be looked in another column. Sorry.

In any case, to you all, thank you very much.
