### ISSUE TITLE
Proposal: Add International Organizations

### ISSUE THREAD

**Issue by dieghernan** [vincentarelbundock/countrycode#257]
Hi!!

I really like this package (in fact it is a dependency of my two CRAN packages). Some time ago I started to put together some code to create this mappings until I discovered this package.

However, there is a piece of work that I haven’t seen anywhere in R, that is a list of the international organisations which each country belongs to:

https://www.cia.gov/-library/publications/the-world-factbook/fields/317.html

I have already a prototype here (https://github.com/dieghernan/Country-Codes-and-International-Organizations/blob/master/outputs/CountrycodesOrgs.csv), so I was wondering if it is something you may consider to include in this package.

If so I could start preparing a PR.

Thanks, and happy new year

**Comment by cjyetman** [comment]
Thanks @dieghernan! Here are my quick thoughts...

1. `countrycode` is usually **very** strict about the source of information it includes, almost always insisting on a first party source... so I don't think the membership info from the CIA could/would be used directly

2. This concept of matching a country to a member organization is problematic for `countrycode` because `countrycode` assumes a one-to-one relationship between codes. Depending on what you want to achieve, my package https://github.com/cjyetman/memberstates might be better suited to this purpose?

**Comment by vincentarelbundock** [comment]
Makes me think of this

https://correlatesofwar.org/data-sets/IGOs/international-organization-v2.3

How does it compare?

**Comment by dieghernan** [comment]
Wow, that's awesome @vincentarelbundock , I would need some time to check. What I found so far is the potential list of Organisations (https://correlatesofwar.org/data-sets/IGOs/codebook-version-3-igo-data/@@download/file/IGO%20Codebook_v3_short%20copy.pdf Appendix A) and it's huge!

I would let you know when I have some news on this.

And thanks @cjyetman for your comment, what I see it's that maybe I might create a separate package (as yours) if this proposal does not fit on `countrycode`

**Comment by dieghernan** [comment]
Hi,

Following @vincentarelbundock mention to IGO on CoW I am putting together a package `igoR`, dedicated to that dataset

https://github.com/dieghernan/igoR

It is still in progress, but I just wanted to share it with you as a follow-up.

Regards

**Comment by dieghernan** [comment]
And now igoR is on CRAN 🎉 https://cran.r-project.org/package=igoR

**Comment by vincentarelbundock** [comment]
Nice work! Bookmarking.
