### ISSUE TITLE
Various changes

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#311]
Samuel via email suggests:

 I do not know the answer yet, but I had a weird meaning unsuccessful behavior with the following country names when using country.name.de                                  

* «Sint Maarten»
*  «Aruba»
* «Curaçao»

There are some missing genc2c, genc3c, iso2c, iso3c, iso3 values for entries countrycode::codelist. Where they deleted because of country divisions/splits? For me the old code is still useful, because of people that have still passports with the old country name. 

* «Yugoslavia»  see https://www.iso.org/obp/ui/#iso:code:3166:YU
* «Netherlands Antilles» see https://www.iso.org/obp/ui/#iso:code:3166:AN 

Is there a solution for groups and regions?

* Group like «Channel Islands» seems to belong to Guernsey GG (see https://de.wikipedia.org/wiki/ISO_3166-2:GG)
* Regions like «Canary Islands/the Canaries» do belong to Spain ES (see ES-CN in https://en.wikipedia.org/wiki/ISO_3166-2:ES ) (but still has an exceptionally reserved alpha2 code reserved for WCO see https://www.iso.org/obp/ui/#iso:code:3166:IC).

**Comment by samkulu** [comment]
Thank you Vincent, for the deployment of latest improvements. 

As soon as I have more time I will have a look into  `custom_match` or `custom_dict` arguments. I have already prepared some other lists (e.g. NATO, INTERPOL, EU27, EFTA, exEFTA, UN, LOCODE) and would be glad that the work is not all gone. 

By the way, I have found this tutorial from Steven V. Miller with the different classification systems: http://svmiller.com/blog/2021/01/a-tutorial-on-state-classification-systems/ From this article I browse to the GENC Webpage (see https://nsgreg.nga.mil/genc/discovery) where I am reading, that GENC is the official profile of ISO3166 for US law and government. (Vincent: "The script to download and clean the genc codes is here if you are curious: https://github.com/vincentarelbundock/countrycode/blob/main/dictionary/get_genc.R "). This is interesting for me, because ...

Switzerland has its own recognition of states and goverments. There PDF-Files in de, fr, it and en can be found here: https://www.eda.admin.ch/eda/en/fdfa/foreign-policy/international-law/respect-promotion/the-recognition-of-states-and-governments.html  
It seems to me that the Swiss FDFA list gets updated 1-3 times a year.  As soon as I have time I intent do create an own R-Function (e.g. get_ch_recognition.R).

**Comment by samkulu** [comment]
Hi Vincent, 

We have found another good source, that seems to incorporated the official Swiss country recognition very well. For hosting a function like the "get_genc.R" this should be much easier to check than a pdf version from the EDA.

https://www.bfs.admin.ch/bfs/de/home/grundlagen/stgb.assetdetail.22870013.html

BFS (Bundesamt für Statistik) is the Federal Statistical Office of Switzerland. Could you have a look into the table and tell me whether it is more efficient to keep it as is? Or do we need to translate it into a custom csv dictionaries?
 

B.R. 
Samuel

**Comment by vincentarelbundock** [comment]
I thought GENC was a US government code list. Are the codes in your link really GENC? What are the differences between those and the ones we already have?

**Comment by vincentarelbundock** [comment]
I have integrated the info in this issue into the relevant other issues. Closing this now to avoid duplication.
