### ISSUE TITLE
No 'wb' to 'iso3c' matches for Andorra, Romania, Timor-Leste and Congo, the Democratic Republic

### ISSUE THREAD

**Issue by ofurkusi** [vincentarelbundock/countrycode#62]
Running version 0.18 from CRAN I get these results:
````{R}
> countrycode(c("AND","ROU","TLS","COD"), origin="wb", destination="iso3c")
[1] NA NA NA NA
````

For these World Bank codes I should be getting the same iso3c codes.

Additionally, the following do not match:
- CHI: Channel Islands
- IMN: Isle of Man
- KSV: Kosovo
- PSE: West Bank and Gaza

According to the [Wikipedia ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) article, these codes don't seem to be official so I don't know what is the proper handling of these codes.

**Comment by NilsEnevoldsen** [comment]
The problem is that these countries have multiple WB codes, and countrycode doesn't have a good way to handle that:

http://api.worldbank.org/countries/and = http://api.worldbank.org/countries/ado
http://api.worldbank.org/countries/rou = http://api.worldbank.org/countries/rom
http://api.worldbank.org/countries/tls = http://api.worldbank.org/countries/tmp
http://api.worldbank.org/countries/cod = http://api.worldbank.org/countries/zar

http://api.worldbank.org/countries/imn = http://api.worldbank.org/countries/imy
http://api.worldbank.org/countries/pse = http://api.worldbank.org/countries/wbg

Kosovo should work, though. That surprises me.

**Comment by vincentarelbundock** [comment]
Thanks for the notice. Since there isn't a super clean option, I'm going to let backward compatibility + inertia guide my decision. I'm pinging this issue from the many-to-one mapping as a use case when I/we refactor.

**Comment by cjyetman** [comment]
[this page](https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-api-country-queries) says that World Bank has:
- 3 letter Code differences: Andorra, Congo, Dem. Rep., Isle of Man, Romania, Timor-Leste, West Bank and Gaza
- 2 letter Code differences: Congo, Dem. Rep., Serbia, Timor-Leste, Yemen, Rep., West Bank and Gaza

however, the codes that the WB API currently returns seem to match iso3c, except for Kosovo (for which there is no 'official' iso3c)...
[http://api.worldbank.org/countries/?format=json&per_page=1000](http://api.worldbank.org/countries/?format=json&per_page=1000)
```r
library(jsonlite)
library(countrycode)
library(dplyr)

jsonurl <- 'http://api.worldbank.org/countries/?format=json&per_page=1000'
df <- jsonlite::fromJSON(jsonurl)[[2]]

wb <- 
  df %>% 
  dplyr::select(name, id, iso2Code) %>% 
  dplyr::mutate(country.name = countrycode(name, 'country.name', 'country.name')) %>% 
  dplyr::filter(!is.na(country.name)) %>% 
  dplyr::filter(name != 'Sub-Saharan Africa excluding South Africa') %>% 
  dplyr::filter(name != 'Sub-Saharan Africa excluding South Africa and Nigeria')

cust_dict <- countrycode_data
matchidxs <- match(cust_dict$country.name.en, wb$country.name)
cust_dict$wb <- wb$id[matchidxs]

exceptions <- (is.na(cust_dict$iso3c) & !is.na(cust_dict$wb)) | 
  (!is.na(cust_dict$iso3c) & !is.na(cust_dict$wb) & cust_dict$iso3c != cust_dict$wb)
cust_dict[exceptions, c('country.name.en', 'iso3c', 'wb')]
```
