### ISSUE TITLE
origin_regex=TRUE to allow regexes in custom dictionary

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#68]
Use same "switch" mechanism for country.name in the main function.

**Comment by cjyetman** [comment]
I propose something like this...
```r
countrycode <- function (sourcevar, origin, destination, warn=FALSE, dictionary=NULL, origin_regex=FALSE){
```
and this near the beginning, before `dictionary` is set to `countrycode::countrycode_data`...
```r
# auto-set origin_regex for regex origins in default dictionary
default_regex_codes <- c('country.name', 'country.name.de')
if (!is.null(dictionary) {
    if (origin %in% default_regex_codes) {
        origin <- paste0(origin, '.regex')
        origin_regex <- TRUE
    } else {
        origin_regex <- FALSE
    }
}
```
and that all codes in the CSV that have a matching regex column be named in the style of 'name.of.code' and 'name.of.code.regex' (only difference being a '.regex' suffix) so that it is very easy to determine the name of the regex version. So you would have to change the name of the 'regex' column in the current CSV to 'country.name.regex'. Also in PR #80, the column names would have to conform to the naming scheme. That would make it easier to add new ones in the future, and make the switching code less verbose.

This essentially ignores `origin_regex` if no custom dictionary is passed, and instead manually sets it based on a predetermined list of codes in the default dictionary that have matching regex versions. If a custom dictionary is passed, then `origin_regex` is assumed to be correct (or FALSE by default if unset).

If the column names in the CSV conform to the naming scheme, you could also search for matching column names and use those for `default_regex_codes` rather than setting it manually. Something like...
```r
default_regex_codes <- sub('\\.regex$', '', grep('\\.regex$', names(countrycode_data), value = TRUE))
```

**Comment by vincentarelbundock** [comment]
Tonight ill be adding coutrynames in arabic, spanish, French and Russian, but they don't have matching regex.  If that renaming scheme can accommodate that, I say go ahead. (At family thing now, so can't think through implications, but I trust you and will merge tonight).

**Comment by vincentarelbundock** [comment]
Same for origin regex. Seems like the best design solution (for now at least).
