### ISSUE TITLE
Add critical cases to the JSON test file

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/countrycode#97]
https://github.com/vincentarelbundock/countrycode/commit/373a2fd867086eeb03087e3bc8dcbd45f98860bb

**Comment by cjyetman** [comment]
the JSON file to add country name variations is here: [tests/testthat/country_name_known_variations.json](https://github.com/vincentarelbundock/countrycode/blob/master/tests/testthat/country_name_known_variations.json)

Note that this file should only have *unambiguous* country name variations. For example, this file should *not* include "Korea" as a variation for "South Korea" because that could also be interpreted as "North Korea".

**Comment by vincentarelbundock** [comment]
For reference, this is probably going to remain open as this should be an ongoing process.

**Comment by vincentarelbundock** [comment]
Germany East
Germany West

**Comment by cjyetman** [comment]
add "Virgin Islands (U.S.)" for "Virgin Islands, U.S."

**Comment by cjyetman** [comment]
1. Is this test broken now that the default country names have possibly changed since the switch to CLDR names?
2. This is technically only testing English names, correct? Maybe that should be very explicit so we know that we are not testing variations in other languages that we support (only German at the moment).

**Comment by vincentarelbundock** [comment]
I fixed all the tests for clrd already.

Being explicit is always good...

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/countrycode/issues/234

https://github.com/vincentarelbundock/countrycode/issues/233
